export const FETCH_ITEMS_LOADING = "FETCH_ITEMS_LOADING";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_ERROR = "FETCH_ITEMS_ERROR";
export const REMOVE_LIST_ITEM = "REMOVE_LIST_ITEM";
export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const TOGGLECHECK_LIST_ITEM = "TOGGLECHECK_LIST_ITEM";
